# Generated by Django 5.1.2 on 2024-10-15 19:05

import django.db.models.deletion # type: ignore
from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="static/logos/")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (
                                "microcontroladores",
                                "ENG4033 – Projeto de Microcontroladores",
                            ),
                            ("matlab", "ENG1118 – Matlab"),
                            ("software", "ENG4021 - Projeto Integrado de Software"),
                        ],
                        max_length=100,
                    ),
                ),
                ("color", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (
                                "microcontroladores",
                                "ENG4033 – Projeto de Microcontroladores",
                            ),
                            ("matlab", "ENG1118 – Matlab"),
                            ("software", "ENG4021 - Projeto Integrado de Software"),
                        ],
                        max_length=100,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "logo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="class_dashboard.logo",
                    ),
                ),
            ],
            options={
                "verbose_name": "class",
                "verbose_name_plural": "classes",
            },
        ),
    ]
