# Generated by Django 5.1.2 on 2024-10-15 19:24

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("class_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logo",
            name="image",
            field=models.ImageField(upload_to="logos/"),
        ),
    ]
